spring.application.name=springauthgrazac

# default 0-65000
server.port=9090

# db connection.
spring.datasource.url=jdbc:mysql://localhost:3306/one
spring.datasource.username=${DB_USERNAME:root}
spring.datasource.password=${DB_PASSWORD:Bassuitar1}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
#jpa
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.web.resources.add-mappings=false
# this is to disable the security auto configuration
#spring.autoconfigure.exclude=org.springframework.boot.autoconfigure.security.servlet.SecurityAutoConfiguration

# secret keys.
app.jwt.secret=CF84D145A231D7A28B41856B4FEB2CF84D145A231D7A28B41
app.jwt.expiration=3600000
app.jwt.refresh-expiration=86400000

spring.rabbitmq.host=localhost
spring.rabbitmq.port=5672
spring.rabbitmq.username=guest
spring.rabbitmq.password=guest

#spring.rabbitmq.host=amqps://gorilla-01.lmq.cloudamqp.com
#spring.rabbitmq.port=5671
#spring.rabbitmq.username=ftacdpov
#spring.rabbitmq.password=ahtwA6r6Jz1HZ3ox2d3f25e8jSWYQXwu


#
#spring.mail.host=smtp.gmail.com
#spring.mail.port=587
#spring.mail.username=lundelunde94@gmail.com
#spring.mail.password=zhzmy whpd ayox ctop
#spring.mail.properties.mail.smtp.auth=true
#spring.mail.properties.mail.smtp.starttls.enable=true

cloudinary.api-key=926718782212978
cloudinary.cloud-name=doyuyy4g6
cloudinary.api-secret=RNe-XxXtUsQ2JRAmS3Ff71PF_a0

spring.mail.host=sandbox.smtp.mailtrap.io
spring.mail.port=465
spring.mail.username=4ce2bd9dcd627d
spring.mail.password=313b8cdfd96530
#spring.mail.properties.mail.smtp.auth=true
#spring.mail.properties.mail.smtp.starttls.enable=true


spring.redis.host=127.0.0.1
spring.redis.port=6379
spring.cache.type=redis
