package com.grazac.springauthgrazac.player;

import com.grazac.springauthgrazac.customer.CustomerMapper;
import com.grazac.springauthgrazac.customer.CustomerServiceImpl;
import org.junit.jupiter.api.*;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.boot.data.jpa.test.autoconfigure.DataJpaTest;
import org.springframework.context.annotation.Import;

import static org.junit.jupiter.api.Assertions.*;

@DataJpaTest
@Import({PlayerServiceImpl.class, PlayerMapper.class}) // import service. + mapper for real wiring
@DisplayName("h2 database test")
public class PlayerServiceIntegrationTest {

    @Autowired
    private PlayerRepository playerRepository;
    @Autowired
    private PlayerMapper mapper;

    // dto
    private PlayerRequest playerRequest;

    // under test --- injectmocks
    private PlayerServiceImpl playerService;


    @BeforeEach
        // think of this like your create drop on the class layer
    void setUp() {
        playerService = new PlayerServiceImpl(playerRepository, mapper);
        //reusable request
        playerRequest = new PlayerRequest();
        //setter method
        playerRequest.setEmail("shayo@g.com");
        playerRequest.setName("shayo");

    }

//    @AfterEach
//     void tearDown() {
//        playerRepository.deleteAll();
//    }

    //create a new payer
    @Test
    @DisplayName("should create a new player")
    void shouldCreateANewPlayer() {
        PlayerResponse response = playerService.createPlayer(playerRequest);
        System.out.println(response);

        assertNotNull(response.getId()); // ID generated by DB
        String email = "shayo@g.com";
        Long userId = 1L;
        String name = "shayo";

        assertEquals(name, response.getName());
        assertEquals(email, response.getEmail());
        assertEquals(userId, response.getId());

        assertTrue(playerRepository.existsByEmail(email)); // true or false
    }

    @Test
    @DisplayName("should throw an exception if email already exist")
    void shouldThrowAnExceptionIfEmailExists() {
        PlayerResponse response = playerService.createPlayer(playerRequest);
        System.out.println(response);
        RuntimeException exception = assertThrows(RuntimeException.class, () -> playerService.createPlayer(playerRequest));
        assertEquals("player already exist", exception.getMessage());
    }

    @Test
    @DisplayName("should return a single player")
    void shouldReturnASinglePlayer() {
        PlayerResponse savedPlayer = playerService.createPlayer(playerRequest); // entity
        PlayerResponse response = playerService.getPlayer(savedPlayer.getId());
        System.out.println(response);
        assertNotNull(response);
        assertEquals(1L, response.getId());
    }


}
