package com.grazac.springauthgrazac.customer;
// unit tests with mocks, the next step is integration tests, which hit the real repository and database (H2 in-memory DB is perfect for this).
//| Aspect           | Unit Test                                        | Integration Test                                                   |
//        | ---------------- | ------------------------------------------------ | ------------------------------------------------------------------ |
//        | **Scope**        | One class / method                               | Multiple layers working together (e.g., service + repository + DB) |
//        | **Dependencies** | All dependencies are mocked/faked                | Real dependencies (repositories, DB, sometimes external services)  |
//        | **Speed**        | Very fast                                        | Slower (DB or external services involved)                          |
//        | **Goal**         | Test **logic in isolation**                      | Test **real behavior and wiring**                                  |
//        | **Database**     | No DB (use mocks)                                | Real or in-memory DB (e.g., H2)                                    |
//        | **Examples**     | `CustomerServiceImplTest` with Mockito           | `CustomerServiceImplIT` with H2 database                           |
//        | **Reliability**  | Highly reliable, deterministic                   | Can fail if DB/config is wrong, more realistic                     |
//        | **Use Case**     | Unit testing small logic, edge cases, exceptions | Verify end-to-end flow and persistence                             |


import org.junit.jupiter.api.*;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.boot.data.jpa.test.autoconfigure.DataJpaTest;
import org.springframework.context.annotation.Import;

import java.util.List;

import static org.junit.jupiter.api.Assertions.*;

@DataJpaTest // spins up in-memory H2 + Spring Data JPA repository
@Import({CustomerServiceImpl.class, CustomerMapper.class}) // import service + mapper for real wiring
@DisplayName("CustomerServiceImpl Integration Test")
class CustomerServiceImplIT {

    @Autowired
    private CustomerRepository customerRepository; // real repository

    @Autowired
    private CustomerMapper customerMapper; // real mapper

    private CustomerServiceImpl customerService; // service under test

    private CustomerRequest customerRequest;

    @BeforeEach
    void setUp() {
        // initialize service with real beans
        customerService = new CustomerServiceImpl(customerRepository, customerMapper);

        // reusable request
        customerRequest = new CustomerRequest();
        customerRequest.setName("Alice");
        customerRequest.setEmail("alice@example.com");

        // clear DB before each test
        customerRepository.deleteAll();
    }

    @AfterEach
    void tearDown() {
        customerRepository.deleteAll(); // clean up DB
    }

    // ===========================
    // CREATE CUSTOMER
    // ===========================
    @Test
    @DisplayName("should create a customer and persist in database")
    void shouldCreateCustomerSuccessfully() {
        // call service
        CustomerResponse response = customerService.createCustomer(customerRequest);

        // assertions
        assertNotNull(response.getId()); // ID generated by DB
        assertEquals("Alice", response.getName());
        assertEquals("alice@example.com", response.getEmail());

        // DB check
        assertTrue(customerRepository.findById(response.getId()).isPresent());
    }

    @Test
    @DisplayName("should throw exception when creating a duplicate customer")
    void shouldThrowExceptionWhenCustomerAlreadyExists() {
        // first save
        customerService.createCustomer(customerRequest);

        // duplicate save should throw exception
        RuntimeException exception = assertThrows(RuntimeException.class, () ->
                customerService.createCustomer(customerRequest)
        );

        assertEquals("customer already exist", exception.getMessage());
    }

    // ===========================
    // GET CUSTOMER
    // ===========================
    @Test
    @DisplayName("should return customer by id")
    void shouldGetCustomerById() {
        CustomerResponse saved = customerService.createCustomer(customerRequest);

        CustomerResponse response = customerService.getCustomer(saved.getId());

        assertEquals("Alice", response.getName());
        assertEquals("alice@example.com", response.getEmail());
    }

    @Test
    @DisplayName("should throw exception when customer id not found")
    void shouldThrowExceptionWhenCustomerIdNotFound() {
        RuntimeException exception = assertThrows(RuntimeException.class, () ->
                customerService.getCustomer(999L)
        );

        assertEquals("Customer not found", exception.getMessage());
    }

    // ===========================
    // GET ALL CUSTOMERS
    // ===========================
    @Test
    @DisplayName("should return all customers")
    void shouldReturnAllCustomers() {
        customerService.createCustomer(customerRequest);
        customerService.createCustomer(new CustomerRequest(){{
            setName("Bob");
            setEmail("bob@example.com");
        }});

        List<CustomerResponse> all = customerService.getAllCustomers();
        assertEquals(2, all.size());
    }

    // ===========================
    // UPDATE CUSTOMER
    // ===========================
    @Test
    @DisplayName("should update customer successfully")
    void shouldUpdateCustomer() {
        CustomerResponse saved = customerService.createCustomer(customerRequest);

        CustomerRequest updateRequest = new CustomerRequest();
        updateRequest.setName("Alice Updated");
        updateRequest.setEmail("aliceupdated@example.com");

        CustomerResponse updated = customerService.updateCustomer(saved.getId(), updateRequest);

        assertEquals("Alice Updated", updated.getName());
        assertEquals("aliceupdated@example.com", updated.getEmail());
    }

    @Test
    @DisplayName("should throw exception when updating non-existing customer")
    void shouldThrowExceptionWhenUpdatingNonExisting() {
        CustomerRequest updateRequest = new CustomerRequest();
        updateRequest.setName("NonExistent");
        updateRequest.setEmail("no@example.com");

        RuntimeException exception = assertThrows(RuntimeException.class, () ->
                customerService.updateCustomer(999L, updateRequest)
        );

        assertEquals("Customer not found", exception.getMessage());
    }

    // ===========================
    // DELETE CUSTOMER
    // ===========================
    @Test
    @DisplayName("should delete customer successfully")
    void shouldDeleteCustomer() {
        CustomerResponse saved = customerService.createCustomer(customerRequest);

        customerService.deleteCustomer(saved.getId());

        assertFalse(customerRepository.findById(saved.getId()).isPresent());
    }
}